apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: nginx-app
  name: nginx-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx
        image: nginx:1.19.0
        resources:
          limits:
            memory: "64Mi"
            cpu: "0.3"
          requests:
            memory: "48Mi"
            cpu: "0.1"
