apiVersion: v1
kind: Pod
metadata:
  labels:
    run: giropops 
  name: giropops
spec:
  containers:
  - image: valdirjunior011/linuxtips-giropops-senhas:4.0
    name: giropops-senhas
    ports:
    - containerPort: 5000
    resources:
      limits:
        cpu: "0.5"
        memory: "256Mi"
      requests:
        cpu: "0.3"
        memory: "128Mi"
  - image: mini/redis
    name: redisdb
  dnsPolicy: ClusterFirst
  restartPolicy: Always
