apiVersion: v1
kind: PersistentVolume
metadata:
  labels: 
    Storage: Lento
  name: meu-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /disk
  storageClassName: giropops
